language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
before-install:
  - echo "Installing..."
install: 
  - npm install --dev -d
  - sudo npm install -g grunt-cli codecov istanbul
script: 
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
  - grunt
